//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControTrafico.Infrastructure.PruebasDaniel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eventlog
    {
        public int id { get; set; }
        public Nullable<System.Guid> idProceso { get; set; }
        public string proceso { get; set; }
        public Nullable<System.DateTime> Tiempo_Control { get; set; }
    }
}
